<?php
echo PHP_EOL;
echo $this->tag->linkTo(
    'signup',
    'Sign Up Here!'
);
?>
<style>
   table {
      width: 700px;
      text-align: center;
      border: 1px solid #fff;
      border-spacing: 1px;
      font-family: 'Cairo', sans-serif;
      margin: auto;
   }

   caption {
      font-weight: bold;
   }

   table td {
      padding: 10px;
      background-color: #eee;
   }

   table th {
      background-color: #333;
      color: #fff;
      padding: 10px;
   }

   img {
      width: 90px;
      height: 90px;
   }

   .view,
   .delete {
      border: none;
      padding: 5px 10px;
      color: #fff;
      font-weight: bold;
   }

   .view {
      background-color: #03A9F4;
   }

   .delete {
      background-color: #E91E63;
   }

   .tablefoot {
      padding: 0;
      border-bottom: 3px solid #009688;
   }

   .overlay {
      position: fixed;
      top: 0;
      bottom: 0;
      left: 0;
      right: 0;
      background: rgba(0, 0, 0, 0.7);
      transition: opacity 500ms;
      visibility: hidden;
      opacity: 0;
   }

   .overlay:target {
      visibility: visible;
      opacity: 1;
   }

   .popup {
      margin: 70px auto;
      padding: 20px;
      background: #fff;
      border-radius: 5px;
      width: 30%;
      position: relative;
      transition: all 5s ease-in-out;
   }

   .popup h2 {
      margin-top: 0;
      color: #333;
      font-family: Tahoma, Arial, sans-serif;
   }

   .popup .close {
      position: absolute;
      top: 20px;
      right: 30px;
      transition: all 200ms;
      font-size: 30px;
      font-weight: bold;
      text-decoration: none;
      color: #333;
   }

   .popup .content {
      max-height: 100%;
      overflow: auto;
   }

   @media screen and (max-width: 700px) {
      .box {
         width: 70%;
      }

      .popup {
         width: 70%;
      }
   }
</style>
<h2 style="margin-left: 40%;">Product Lists</h2>
<form method="POST" action="" style="margin-left: 35%;">
   <input type="text" name="search_field" id="">
   <input type="submit" value="search" name="search">
   <input type="submit" value="all" name="all_product"><br><br>
</form>
<table>
   <thead>
      <tr>

         <th>Product Name</th>
         <th>Category Name</th>
         <th>Price</th>
         <th>Stock</th>
         <th>Action</th>
      </tr>
   </thead>
   <tbody>
      <?php foreach ($table as $value) { ?>
         <tr>
            <td><?php echo $value->product_name; ?></td>
            <td><?php echo $value->category_name; ?></td>
            <td><?php echo $value->price; ?></td>
            <td><?php echo $value->stock;
                  ?></td>
            <!-- <td><a href="/admin/addproduct/index?id=<?php echo $value->_id; ?>">edit</a></td>
            <td><a href="/admin/displayproduct/delete?id=<?php echo $value->_id; ?>">delete</a></td> -->
            <td>
               <a class="button" href="#<?php echo $value->_id; ?>">view</a>

               <div id="<?php echo $value->_id; ?>" class="overlay">
                  <div class="popup">
                     <h2><u>Metafields</u></h2>
                     <a class="close" href="#">&times;</a>
                     <div class="content">
                        <?php
                        echo "<h4>Label</h4>";
                        foreach ($value->label_value as $val) {
                           echo 'label : ' . $val->label;
                           echo 'value : ' . $val->value;

                           echo "<br>";
                        }
                        foreach ($value->variation as $val) {
                           echo 'name : ' . $val->name;
                           echo 'value : ' . $val->value;
                           echo 'price : ' . $val->price;

                           echo "<br>";
                        } ?>

                     </div>
                  </div>
               </div>
            </td>
         </tr>
      <?php } ?>

   </tbody>
   <tfoot>
      <td colspan="5" class="tablefoot"></td>
   </tfoot>
</table>